#!/bin/bash



cdd(){
    local slum_main_path=~/code/slum
    local slum_goto_path="$slum_main_path/goto"

    #============================ cdd ================================#
    # 1. get pathname
    # 2. get realpath by pathname
    # 3. cd realpath
    # cd $1
    #==================================================================#


    #============================ goto ================================#
    if [ $1 = "read" ]; then
        slum goto read
        return
    fi

    slum goto get $1
    return 0
   #==================================================================#
}